### ISSUE TITLE
Deploying Nuxt Mail to Cloudflare pages

### ISSUE THREAD

**Issue by mattgrah-am** [dword-design/nuxt-mail#236]
Has anyone had any success using this module with Cloudflare pages?

When I try to deploy via a Github repo I get the following error at the end of the deployment:

```
Error: Failed to publish your Function. Got error: Uncaught TypeError: Class extends value #<Object> is not a constructor or null
  at chunks/runtime.mjs:17962:20
```

Deploying it via wrangler provides a little more detail:
```
✘ [ERROR] service core:user:worker: Uncaught TypeError: Class extends value #<Object> is not a constructor or null

    at null.<anonymous> (h0rrzz8k09m.js:15527:5) in .wrangler/tmp/pages-LwLK14/chunks/runtime.mjs
    at null.<anonymous> (h0rrzz8k09m.js:4:59) in __init
    at null.<anonymous> (h0rrzz8k09m.js:17973:1)


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

**Comment by MrBolux** [comment]
Hello, I have the same problem after searching all afternoon I found this :

https://github.com/nodemailer/nodemailer/issues/1623

**Comment by vogonwann** [comment]
Hello, I have the same problem. Is there a solution?

```Error: Failed to publish your Function. Got error: Uncaught TypeError: Class extends value #<Object> is not a constructor or null
  at chunks/nitro/nitro.mjs:1:302602

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    ... 4 lines matching cause stack trace ...
    at async runMain (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/citty/dist/index.mjs:445:7) {
  [cause]: Error: - Error: Failed to publish your Function. Got error: Uncaught TypeError: Class extends value #<Object> is not a constructor or null
    at chunks/nitro/nitro.mjs:1:302602
  
      at onResponseError (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/nuxthub/src/utils/data.mjs:21:19)
      at callHooks (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:134:13)
      at $fetchRaw2 (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:306:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async $fetch2 (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:316:15)
      at async Object.run (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/nuxthub/src/commands/deploy.mjs:198:20)
      at async runCommand (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/citty/dist/index.mjs:316:16)
      at async runCommand (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/citty/dist/index.mjs:307:11)
      at async runMain (file:///home/wann/.npm/_npx/0fa85d1aa04cf089/node_modules/citty/dist/index.mjs:445:7)
}

 ERROR  Failed to publish your Function. Got error: Uncaught Type     ```

**Comment by L422Y** [comment]
You might have better results with https://github.com/zou-yu/worker-mailer

**Comment by kalnode** [comment]
For the time being I've dropped this module in favour of just some custom scripts.

Not elegant at all, but works.

**For local:** uses `nodemailer`
**For Cloudflare prod:** uses `worker-mailer`

I didn't account for other contexts. In theory I think a deploy elsewhere may work fine with nodemailer.

Only tested Gmail smtp.

Works on both my local and in a Cloudflare deploy; I'm able to send emails to Gmail smtp from a contact page.

See:
https://gist.github.com/kalnode/459d9e02a2e0abfd7e3280448f3d3dee
